#!/usr/bin/env python3
# Generate Mia's English lessons 21-50 by cloning the a1s_03 template and
# swapping only the variable blocks. Engine/CSS/warm-up/words panels stay identical.
import re, os
DIR = "/Users/malcolmtheteacher/Documents/01_Work/gitsite"
TPL = open(os.path.join(DIR, "a1s_03_where.html"), encoding="utf-8").read()

M1 = "mia_english_dashboard.html"      # morelink 1 (always exists)
M2 = "CEFR_Grammar_Dashboard.html"     # morelink 2 (always exists)

def story_html(img1, alt1, img2, alt2, lines):
    half = max(1, len(lines)*2//3)
    top = "".join("            <p>%s</p>\n" % l for l in lines[:half])
    bot = "".join("            <p>%s</p>\n" % l for l in lines[half:])
    return (
        '            <img class="scene" src="%s" alt="%s" onerror="ph(this)">\n%s'
        '            <img class="scene" src="%s" alt="%s" onerror="ph(this)">\n%s'
        % (img1, alt1, top, img2, alt2, bot))

def build_file(n, slug, title, sub, story_h2, story_lines, img1, alt1, img2, alt2,
               tip1, pat_h2, pat_build, pat_tip, yt_lead, yt_build, yt_label, yt_ph,
               checklist, words):
    name = "Lesson %d · %s" % (n, title)
    s = TPL
    # title + meta
    s = s.replace("<title>Mia's English · Lesson 3 · Where is it?</title>",
                  "<title>Mia's English · Lesson %d · %s</title>" % (n, title))
    s = re.sub(r'<meta name="description"[^>]*>',
               '<meta name="description" content="Mia\'s English — Lesson %d: %s. %s">' % (n, title, sub.replace('"',"'")),
               s, count=1)
    # header block
    s = re.sub(r'<header>.*?</header>',
        '<header>\n        <div class="step">Mia\'s English · Lesson %d</div>\n'
        '        <h1>%s</h1>\n        <p>%s</p>\n    </header>' % (n, title, sub),
        s, count=1, flags=re.S)
    # story panel (between <!-- STORY --> and <!-- WORDS -->)
    story = (
        '    <!-- STORY -->\n    <div class="panel" id="p1">\n'
        '        <h2>%s <span class="em">📖</span></h2>\n'
        '        <p class="lead">Read it slowly. Say the words out loud.</p>\n'
        '        <div class="story">\n%s        </div>\n'
        '        <div class="tip"><b>Notice:</b> %s</div>\n'
        '        <div class="center"><button class="btn btn-primary" onclick="showTab(2)">Learn the words →</button></div>\n'
        '    </div>\n\n' % (story_h2, story_html(img1, alt1, img2, alt2, story_lines), tip1))
    s = re.sub(r'    <!-- STORY -->.*?\n\n(    <!-- WORDS -->)', story + r'\1', s, count=1, flags=re.S)
    # pattern panel
    pat = (
        '    <!-- PATTERN -->\n    <div class="panel" id="p3">\n'
        '        <h2>%s <span class="em">🧩</span></h2>\n'
        '        <p class="lead">Look at the pattern, then use it.</p>\n'
        '        <div class="build">\n%s        </div>\n'
        '        <div class="tip">%s</div>\n'
        '        <a class="morelink" href="%s">🗺️ <span>Back to all Mia lessons</span><span class="go">Open →</span></a>\n'
        '        <a class="morelink" href="%s">📚 <span>The full grammar course</span><span class="go">Open →</span></a>\n'
        '    </div>\n\n' % (pat_h2, pat_build, pat_tip, M1, M2))
    s = re.sub(r'    <!-- PATTERN -->.*?\n\n(    <!-- YOUR TURN -->)', pat + r'\1', s, count=1, flags=re.S)
    # your turn panel
    checks = "".join("            <li>%s</li>\n" % c for c in checklist)
    yt = (
        '    <!-- YOUR TURN -->\n    <div class="panel" id="p4">\n'
        '        <h2>Now you <span class="em">🗣️</span></h2>\n'
        '        <p class="lead">%s</p>\n'
        '        <div class="build">\n%s        </div>\n'
        '        <label class="f">%s</label>\n'
        '        <input class="blank" placeholder="%s">\n\n'
        '        <h3 style="color:var(--teal-d);margin:18px 0 6px;">Practise today\'s words</h3>\n'
        '        <p class="lead" style="margin-bottom:8px">Tap to check yourself, then rate how well you knew each one.</p>\n'
        '        <div class="center"><button class="btn btn-ghost" onclick="reviewToday()">Review today\'s words 🔁</button></div>\n'
        '        <div id="turnReview" style="margin-top:14px"></div>\n\n'
        '        <h3 style="color:var(--teal-d);margin:18px 0 6px;">Before you go</h3>\n'
        '        <ul class="checklist">\n%s        </ul>\n'
        '        <div class="tip" style="margin-top:16px"><b>See you next time.</b> Today\'s words join your Warm-up. Little by little, they become yours forever. 🔁</div>\n'
        '    </div>\n\n' % (yt_lead, yt_build, yt_label, yt_ph, checks))
    s = re.sub(r'    <!-- YOUR TURN -->.*?\n\n(    <footer>)', yt + r'\1', s, count=1, flags=re.S)
    # footer
    s = s.replace("<footer>Mia's English · A1 Story Journey · Lesson 3</footer>",
                  "<footer>Mia's English · A1 Story Journey · Lesson %d</footer>" % n)
    # LESSON_NAME + array
    s = s.replace('var LESSON_NAME="Lesson 3 · Where is it?";',
                  'var LESSON_NAME="%s";' % name)
    arr = "var LESSON=[\n" + "".join(
        "    ['%s',\"%s\",'%s','%s'],\n" % (w[0], w[1], w[2], w[3]) for w in words) + "];"
    s = re.sub(r'var LESSON=\[.*?\];', arr, s, count=1, flags=re.S)
    open(os.path.join(DIR, "a1s_%02d_%s.html" % (n, slug)), "w", encoding="utf-8").write(s)
    return "a1s_%02d_%s.html" % (n, slug), name, [w[1] for w in words]

# ---- content for lessons 21-50 ----
def w(i,f,b,e): return ("l%d_%s"%(i,re.sub(r'[^a-z]','',f.lower())[:8] or "w"), f, b, e)
L = []
def add(**k): L.append(k)

add(n=21, slug="flat", title="The little flat", sub="Talk about your home with have got.",
 story_h2="A home of her own", img1="a1s_21_flat.png", alt1="Mia opens the door of a small empty flat, light pouring in, thrilled; Tom carries a box.",
 img2="a1s_21_home.png", alt2="The flat is now cosy: plants, a teal rug, fairy lights; Mia hangs a picture.",
 story_lines=["Big news! Mia has got a little <b>flat</b> now. It is above the bookshop. 🏠",
  "It is small, but it is hers. Tom helps her. He carries a big <b>box</b>.",
  '<span class=say>"It has got two rooms and a tiny kitchen,"</span> says Mia. <span class=say>"I love it!"</span>',
  "At first the flat is empty. It has not got a sofa. It has not got plants.",
  "But Mia works hard. She buys a teal <b>rug</b> and some green plants. 🌿",
  "She hangs a picture on the <b>wall</b>. Now the flat is warm and cosy.",
  '<span class=say>"Have you got everything?"</span> asks Tom. <span class=say>"Yes! Now it is home,"</span> says Mia. 🌱'],
 tip1="we use <b>have got</b> to say what we have. <i>I have got a flat. It has got two rooms.</i>",
 pat_h2="The pattern: <i>have got</i>", pat_build='            <b>I have got</b> a flat. → <b>I\'ve got</b> a flat.<br>\n            <b>It has got</b> two rooms. → <b>It\'s got</b> two rooms.<br>\n            <b>Have you got</b> a garden? — No, I <b>haven\'t</b>.\n',
 pat_tip="<b>Picture it:</b> I\'ve got 🔑 · she\'s got 📚 · it\'s got 🌿 · they\'ve got 🛋️.",
 yt_lead="Think about your home. Fill the gaps, then say each one out loud.",
 yt_build='            I have got <input class="blank" style="width:auto;display:inline-block" placeholder="a flat / a house / a room">.<br><br>\n            My home has got <input class="blank" style="width:auto;display:inline-block" placeholder="two rooms / a kitchen…">.\n',
 yt_label="Now write 3 things your home has got:", yt_ph="My home has got …",
 checklist=["I can use <i>I\'ve got</i> and <i>it\'s got</i>","I can ask <i>Have you got…?</i>","I can talk about my home 🏠","My new words are saved 🔁"],
 words=[w(21,"a flat","a home in a building, on one floor","🏠"),w(21,"a room","one part of a home","🚪"),
  w(21,"a wall","the side of a room","🧱"),w(21,"a box","you put things in it to carry them","📦"),
  w(21,"a rug","a small soft mat on the floor","🟦"),w(21,"a plant","it is green and grows","🌿"),
  w(21,"empty","with nothing in it","⬜"),w(21,"have got","use this to say what you have","🙌")])

add(n=22, slug="fridge", title="The empty fridge", sub="Talk about food with some and any.",
 story_h2="Is there any milk?", img1="a1s_22_fridge.png", alt1="Mia peers into an almost-empty fridge — one egg, one lonely tomato — with comic dismay.",
 img2="a1s_22_list.png", alt2="Mia writes a shopping list at her kitchen table, pencil on her chin.",
 story_lines=["It is Mia's first morning in the flat. She is hungry. 🍳",
  "She opens the <b>fridge</b>. Oh no! There is one <b>egg</b>. There is one sad tomato.",
  '<span class=say>"There isn\'t <b>any</b> milk!"</span> says Mia. <span class=say>"There isn\'t any bread!"</span>',
  "There is some <b>butter</b>, but there isn't any cheese. The fridge is nearly empty.",
  "Mia sits down. She takes a pencil and some paper. She writes a shopping <b>list</b>. 📝",
  "<b>Some</b> milk, some bread, some fruit, some rice… the list gets long!",
  '<span class=say>"Today I go shopping,"</span> she says. <span class=say>"I need everything!"</span> 🛒'],
 tip1="we use <b>some</b> and <b>any</b> for food. <i>some</i> in + sentences, <i>any</i> in − and ? sentences.",
 pat_h2="The pattern: <i>some / any</i>", pat_build='            There is <b>some</b> butter. (+)<br>\n            There isn\'t <b>any</b> milk. (−)<br>\n            Is there <b>any</b> bread? (?)\n',
 pat_tip="<b>Remember:</b> <i>some</i> for yes 👍 · <i>any</i> for no 👎 and questions ❓.",
 yt_lead="Look in your kitchen. What is there? Fill the gaps, then say them out loud.",
 yt_build='            There is <input class="blank" style="width:auto;display:inline-block" placeholder="some…"> in my kitchen.<br><br>\n            There isn\'t <input class="blank" style="width:auto;display:inline-block" placeholder="any…">.\n',
 yt_label="Write a short shopping list (3 things you need):", yt_ph="I need some …",
 checklist=["I can use <i>some</i> and <i>any</i>","I can say what food I have","I can write a shopping list 📝","My new words are saved 🔁"],
 words=[w(22,"a fridge","it keeps your food cold","🧊"),w(22,"milk","a white drink from cows","🥛"),
  w(22,"bread","you make sandwiches with it","🍞"),w(22,"an egg","a hen gives you this","🥚"),
  w(22,"butter","yellow, you put it on bread","🧈"),w(22,"a list","words you write to remember","📝"),
  w(22,"some","a little, in + sentences","➕"),w(22,"any","in − sentences and questions","❓")])

add(n=23, slug="shopping", title="The big shop", sub="Shop for the week: how much and how many.",
 story_h2="How much? How many?", img1="a1s_23_trolley.png", alt1="Mia and Tom push a very full supermarket trolley; Tom balances a huge watermelon on top.",
 img2="a1s_23_kitchen.png", alt2="Mia's kitchen counter covered with shopping bags and colourful groceries; the ginger cat inspects a bag.",
 story_lines=["Tom helps Mia do the big <b>shop</b> for the flat. They go to the supermarket. 🛒",
  "The <b>trolley</b> gets very full! Bread, rice, fruit, and a huge <b>watermelon</b>.",
  '<span class=say>"<b>How many</b> eggs do we need?"</span> asks Tom. <span class=say>"Ten, please,"</span> says Mia.',
  '<span class=say>"And <b>how much</b> rice?"</span> <span class=say>"One big bag,"</span> she says.',
  "At the <b>till</b>, Mia pays. It is a lot of money, but now the flat is full of food! 💰",
  "Back home, the ginger cat looks in every bag. 🐈",
  '<span class=say>"Thank you, Tom,"</span> says Mia. <span class=say>"Now I can cook!"</span> 🍚'],
 tip1="<b>how much</b> for things we can't count (rice, milk); <b>how many</b> for things we can count (eggs, apples).",
 pat_h2="The pattern: <i>how much / how many</i>", pat_build='            <b>How much</b> rice? &nbsp;·&nbsp; <b>How much</b> milk? (can\'t count)<br>\n            <b>How many</b> eggs? &nbsp;·&nbsp; <b>How many</b> apples? (can count)\n',
 pat_tip="<b>Count it?</b> apples 🍎🍎 → <i>how many</i> · <b>Can\'t count it?</b> rice 🍚 → <i>how much</i>.",
 yt_lead="Imagine your shopping. Fill the gaps, then say them out loud.",
 yt_build='            <input class="blank" style="width:auto;display:inline-block" placeholder="How much / How many"> bread?<br><br>\n            <input class="blank" style="width:auto;display:inline-block" placeholder="How much / How many"> bananas?\n',
 yt_label="Write 3 questions with how much / how many:", yt_ph="How many … ?",
 checklist=["I can ask <i>How much…?</i>","I can ask <i>How many…?</i>","I can do my shopping in English 🛒","My new words are saved 🔁"],
 words=[w(23,"a shop","you buy things here","🏬"),w(23,"a trolley","you push it and put food in it","🛒"),
  w(23,"rice","small white grains you cook","🍚"),w(23,"a bag","you carry your shopping in it","🛍️"),
  w(23,"a till","where you pay in a shop","💳"),w(23,"how much","for things you can't count","💧"),
  w(23,"how many","for things you can count","🔢"),w(23,"to pay","to give money for things","💰")])

add(n=24, slug="compare", title="Two markets", sub="Compare things: bigger, cheaper, better.",
 story_h2="Which one is better?", img1="a1s_24_two_stalls.png", alt1="Two market stalls side by side — one big and gleaming, one small and charming; Mia stands between them thinking.",
 img2="a1s_24_choice.png", alt2="Mia happily buys from the small stall; the elderly stallholder beams.",
 story_lines=["There is a new supermarket in town. It is big and <b>bright</b>. ✨",
  "But Mia also loves the small old <b>market</b>. She stands between them and thinks.",
  '<span class=say>"The supermarket is <b>bigger</b>,"</span> she says. <span class=say>"And it is <b>cheaper</b>."</span>',
  "But the small market is <b>friendlier</b>. The fruit is <b>fresher</b>. And she knows the people. 🍎",
  "The old man at the stall smiles. <span class=say>\"Good morning, Mia!\"</span> he says.",
  "Mia thinks about it. Cheaper is good. But friendly is <b>better</b> for her.",
  "She buys her apples from the small stall. <span class=say>\"See you next week!\"</span> she says. 😊"],
 tip1="to compare two things, we add <b>-er</b>: big → big<b>ger</b>, cheap → cheap<b>er</b>. And <i>good → better</i>.",
 pat_h2="The pattern: comparatives (<i>-er</i>)", pat_build='            big → <b>bigger</b> &nbsp;·&nbsp; cheap → <b>cheaper</b> &nbsp;·&nbsp; fresh → <b>fresher</b><br>\n            friendly → <b>friendlier</b> &nbsp;·&nbsp; good → <b>better</b> &nbsp;·&nbsp; bad → <b>worse</b><br>\n            The market is <b>cheaper than</b> the shop.\n',
 pat_tip="<b>Two things?</b> add <i>-er</i> and <i>than</i>. <i>The cat is smaller than the dog.</i>",
 yt_lead="Compare two things you know. Fill the gaps, then say them out loud.",
 yt_build='            A bus is <input class="blank" style="width:auto;display:inline-block" placeholder="bigger / smaller…"> than a car.<br><br>\n            My town is <input class="blank" style="width:auto;display:inline-block" placeholder="…er"> than a big city.\n',
 yt_label="Write 3 sentences comparing two things:", yt_ph="A … is …er than a …",
 checklist=["I can add <i>-er</i> to compare","I can use <i>better</i> and <i>worse</i>","I can say what I like more 😊","My new words are saved 🔁"],
 words=[w(24,"bigger","more big","🐘"),w(24,"cheaper","less money","🪙"),
  w(24,"fresher","more new and good (food)","🍎"),w(24,"friendlier","more kind and warm","😊"),
  w(24,"better","more good","👍"),w(24,"than","use it to compare: bigger THAN","⚖️"),
  w(24,"bright","full of light","✨"),w(24,"to choose","to pick the one you want","👉")])

add(n=25, slug="best", title="The best coffee in town", sub="Say the most: the best, the oldest.",
 story_h2="The proudest day", img1="a1s_25_prize.png", alt1="Rosa proudly polishes a little wooden coffee-cup trophy on the counter; Mia and Tom cheer.",
 img2="a1s_25_queue.png", alt2="A cheerful queue of townspeople stretches out of the café door; Rosa and Mia grin behind the counter.",
 story_lines=["Today is a big day at the café! The town newspaper is here. 📰",
  "It says Rosa's café has <b>the best</b> coffee in town! Rosa is so happy. ☕",
  '<span class=say>"We are <b>the best</b>!"</span> she says. <span class=say>"And we have <b>the oldest</b> coffee machine, too!"</span>',
  "Mia and Tom <b>cheer</b>. Rosa gets a little <b>prize</b> — a small wooden cup.",
  "All day, people come. The <b>queue</b> is very long! It goes out of the door.",
  "It is <b>the busiest</b> day of the year. But Rosa smiles all the time. 😊",
  '<span class=say>"This is <b>the happiest</b> day,"</span> she says. <span class=say>"Thank you, everyone!"</span> 🏆'],
 tip1="to say the most, we add <b>the …-est</b>: old → <b>the oldest</b>. And <i>good → the best</i>.",
 pat_h2="The pattern: superlatives (<i>the …-est</i>)", pat_build='            old → <b>the oldest</b> &nbsp;·&nbsp; busy → <b>the busiest</b> &nbsp;·&nbsp; happy → <b>the happiest</b><br>\n            good → <b>the best</b> &nbsp;·&nbsp; bad → <b>the worst</b><br>\n            It is <b>the best</b> coffee in town.\n',
 pat_tip="<b>The most of all?</b> add <i>the …-est</i>. <i>Everest is the highest mountain.</i>",
 yt_lead="Think about your favourites. Fill the gaps, then say them out loud.",
 yt_build='            My favourite café has <input class="blank" style="width:auto;display:inline-block" placeholder="the best…">.<br><br>\n            My town has <input class="blank" style="width:auto;display:inline-block" placeholder="the oldest / biggest…">.\n',
 yt_label="Write 3 sentences with the …-est or the best:", yt_ph="… is the …est …",
 checklist=["I can use <i>the …-est</i>","I can use <i>the best</i>","I can talk about my favourites 🏆","My new words are saved 🔁"],
 words=[w(25,"the best","the most good","🏆"),w(25,"a prize","you win it for being very good","🥇"),
  w(25,"a queue","a line of people waiting","🚶"),w(25,"a newspaper","you read the news in it","📰"),
  w(25,"to cheer","to shout because you are happy","🎉"),w(25,"the oldest","the most old","🏛️"),
  w(25,"the busiest","the most busy","🐝"),w(25,"proud","very happy about something good you did","😊")])

add(n=26, slug="lost", title="The lost tourist", sub="Give directions: turn left, go straight.",
 story_h2="This way, please!", img1="a1s_26_lost.png", alt1="A confused tourist with a backpack holds an upside-down paper map and stops Mia on a street corner.",
 img2="a1s_26_point.png", alt2="Mia confidently points the way down the street; the tourist smiles with relief.",
 story_lines=["Mia walks in town. A <b>tourist</b> stops her. She looks lost. 🗺️",
  '<span class=say>"Excuse me,"</span> says the tourist. <span class=say>"Where is the station, please?"</span>',
  "Mia smiles. Once, she was new here too. Now she knows the way!",
  '<span class=say>"<b>Go straight</b> down this street,"</span> she says. <span class=say>"Then <b>turn left</b> at the café."</span>',
  '<span class=say>"<b>Turn right</b> at the park. The station is <b>on your left</b>,"</span> says Mia.',
  "The tourist is happy. <span class=say>\"Thank you so much!\"</span> she says.",
  "Mia feels proud. Her first directions in English! <span class=say>\"You're welcome,\"</span> she says. 😊"],
 tip1="for directions we use <b>go straight</b>, <b>turn left</b>, <b>turn right</b>. They tell you the way.",
 pat_h2="The pattern: giving directions", pat_build='            <b>Go straight</b> down the street. →<br>\n            <b>Turn left</b> at the café. ↰ &nbsp;·&nbsp; <b>Turn right</b> at the park. ↱<br>\n            It is <b>on your left</b>. &nbsp;·&nbsp; It is <b>on your right</b>.\n',
 pat_tip="<b>Point it out:</b> straight ⬆️ · left ↰ · right ↱ · on your left 👈.",
 yt_lead="A friend asks for the shop near you. Fill the gaps, then say them out loud.",
 yt_build='            <input class="blank" style="width:auto;display:inline-block" placeholder="Go straight / Turn left…"> down my street.<br><br>\n            Then <input class="blank" style="width:auto;display:inline-block" placeholder="turn left / turn right"> at the corner.\n',
 yt_label="Write directions from your home to a shop (3 steps):", yt_ph="Go straight, then …",
 checklist=["I can say <i>go straight</i>","I can say <i>turn left / right</i>","I can help a lost person 🗺️","My new words are saved 🔁"],
 words=[w(26,"a tourist","a visitor from another place","🎒"),w(26,"straight","not left, not right — forward","⬆️"),
  w(26,"left","this side ←","👈"),w(26,"right","this side →","👉"),
  w(26,"to turn","to change the way you go","↩️"),w(26,"a corner","where two streets meet","📐"),
  w(26,"the way","how you get somewhere","🧭"),w(26,"lost","you don't know where you are","❓")])

add(n=27, slug="run", title="The morning run", sub="Say how you move: across, through, up, past.",
 story_h2="Across the bridge", img1="a1s_27_run.png", alt1="Mia jogs across the old stone bridge in morning mist, ducks flying past.",
 img2="a1s_27_route.png", alt2="Mia jogs up the hill with the castle above her, sunrise behind.",
 story_lines=["Every morning, Mia goes for a <b>run</b>. She loves the quiet town. 🏃‍♀️",
  "She runs <b>across</b> the old bridge. The ducks fly <b>past</b> her. 🦆",
  "She runs <b>through</b> the green park. The grass is wet with morning rain.",
  "Then she runs <b>up</b> the big hill. It is hard! But she is strong now.",
  "At the top, she can see the castle and all the town. It is beautiful. 🌅",
  "She runs back <b>down</b> the hill and home. Now she is ready for the day.",
  '<span class=say>"A run in the morning is the best,"</span> says Mia. ☀️'],
 tip1="little words show how we move: <b>across</b> a bridge, <b>through</b> a park, <b>up</b> a hill, <b>past</b> a shop.",
 pat_h2="The pattern: movement words", pat_build='            run <b>across</b> the bridge → &nbsp;·&nbsp; run <b>through</b> the park →<br>\n            run <b>up</b> the hill ↗ &nbsp;·&nbsp; run <b>down</b> the hill ↘<br>\n            run <b>past</b> the shop (go by it) →\n',
 pat_tip="<b>See it move:</b> across a river 🌉 · through a door 🚪 · up stairs ⬆️ · past a café ☕.",
 yt_lead="Think about your way to school or work. Fill the gaps, then say them out loud.",
 yt_build='            I go <input class="blank" style="width:auto;display:inline-block" placeholder="across / through / past…"> the park.<br><br>\n            I walk <input class="blank" style="width:auto;display:inline-block" placeholder="up / down / past…"> the street.\n',
 yt_label="Write 3 sentences about how you move to a place:", yt_ph="I go through / across / up …",
 checklist=["I can use <i>across, through</i>","I can use <i>up, down, past</i>","I can describe my journey 🏃","My new words are saved 🔁"],
 words=[w(27,"a run","when you run for exercise","🏃"),w(27,"across","from one side to the other","🌉"),
  w(27,"through","in one side and out the other","🚪"),w(27,"up","to a higher place","⬆️"),
  w(27,"down","to a lower place","⬇️"),w(27,"past","to go by something","➡️"),
  w(27,"a bridge","it goes over a river","🌉"),w(27,"the top","the highest part","⛰️")])

add(n=28, slug="hobbies", title="Hobby night", sub="Say what you love doing: like / love + -ing.",
 story_h2="What do you love doing?", img1="a1s_28_hobby.png", alt1="Evening hobby night in the café: Tom painting, Rosa knitting, Mia strumming a guitar, all cosy.",
 img2="a1s_28_guitar.png", alt2="Mia practising guitar by her window at home, the ginger cat listening, musical notes floating.",
 story_lines=["On Wednesday, the café has a <b>hobby</b> night. Everyone brings something they love. 🎨",
  "Tom loves <b>painting</b>. He paints a small picture of the bridge.",
  "Rosa loves <b>knitting</b>. She makes a warm scarf, red and gold. 🧣",
  '<span class=say>"I love <b>reading</b>,"</span> says Mia. <span class=say>"But tonight I want to try the <b>guitar</b>!"</span> 🎸',
  "She plays slowly. It is not perfect, but everyone claps.",
  '<span class=say>"I really <b>enjoy</b> this!"</span> she laughs. <span class=say>"I like playing music!"</span>',
  "At home, she plays again. The ginger cat listens. 🎵"],
 tip1="after <b>like</b>, <b>love</b>, <b>enjoy</b>, we use the verb + <b>-ing</b>. <i>I love reading. She likes painting.</i>",
 pat_h2="The pattern: <i>like / love + -ing</i>", pat_build='            I <b>love</b> read<b>ing</b>. &nbsp;·&nbsp; I <b>like</b> paint<b>ing</b>.<br>\n            She <b>enjoys</b> knit<b>ting</b>. &nbsp;·&nbsp; He <b>hates</b> wait<b>ing</b>.<br>\n            Do you <b>like</b> danc<b>ing</b>?\n',
 pat_tip="<b>After like/love:</b> add <i>-ing</i>. <i>I love cooking 🍳 · I hate cleaning 🧹.</i>",
 yt_lead="Think about your hobbies. Fill the gaps, then say them out loud.",
 yt_build='            I love <input class="blank" style="width:auto;display:inline-block" placeholder="reading / cooking / …ing">.<br><br>\n            I don\'t like <input class="blank" style="width:auto;display:inline-block" placeholder="…ing">.\n',
 yt_label="Write 3 things you like or love doing:", yt_ph="I like / love …ing",
 checklist=["I can use <i>love + -ing</i>","I can say what I don't like","I can talk about my hobbies 🎨","My new words are saved 🔁"],
 words=[w(28,"a hobby","something you love to do in your free time","🎨"),w(28,"to paint","to make a picture with colours","🖌️"),
  w(28,"to read","to look at words in a book","📖"),w(28,"to play","to make music, or a game","🎸"),
  w(28,"a guitar","a music thing with strings","🎸"),w(28,"to enjoy","to have a good time doing it","😊"),
  w(28,"free time","time when you don't work","🕰️"),w(28,"to clap","to hit your hands together 👏","👏")])

add(n=29, slug="wish", title="The savings jar", sub="Say your dreams: want to / would like to.",
 story_h2="A little dream", img1="a1s_29_dream.png", alt1="Mia gazes at a travel-agency window full of pretty destination pictures, dreamy expression.",
 img2="a1s_29_jar.png", alt2="Mia drops a coin into a glass savings jar half full of coins, with a determined smile.",
 story_lines=["Mia walks past a travel shop. In the window, she sees the sea and mountains. 🏔️",
  '<span class=say>"One day, I <b>want to</b> travel,"</span> she thinks. <span class=say>"I <b>would like to</b> see the world."</span>',
  "It is only a small <b>dream</b> now. But dreams need a plan!",
  "At home, Mia finds an empty glass <b>jar</b>. She puts it on the shelf.",
  "Every day, she puts a <b>coin</b> in the jar. Clink! 🪙 A little today, a little tomorrow.",
  "The jar gets fuller and fuller. Slowly, the dream comes closer.",
  '<span class=say>"I would like to go somewhere warm,"</span> she smiles. <span class=say>"Soon!"</span> ✨'],
 tip1="to say what you want, use <b>want to</b> or the more polite <b>would like to</b> + a verb.",
 pat_h2="The pattern: <i>want to / would like to</i>", pat_build='            I <b>want to</b> travel. &nbsp;·&nbsp; I <b>would like to</b> travel. (more polite)<br>\n            She <b>wants to</b> learn. &nbsp;·&nbsp; <b>Would</b> you <b>like to</b> come?<br>\n            I <b>\'d like to</b> see the sea.\n',
 pat_tip="<b>Polite wish:</b> <i>I\'d like to…</i> · <i>Would you like to…?</i> 🙂",
 yt_lead="Think about your dreams. Fill the gaps, then say them out loud.",
 yt_build='            One day, I want to <input class="blank" style="width:auto;display:inline-block" placeholder="travel / learn / see…">.<br><br>\n            I would like to <input class="blank" style="width:auto;display:inline-block" placeholder="go to / visit…">.\n',
 yt_label="Write 3 things you would like to do one day:", yt_ph="I would like to …",
 checklist=["I can use <i>want to</i>","I can use <i>would like to</i>","I can talk about my dreams ✨","My new words are saved 🔁"],
 words=[w(29,"a dream","something you hope to do one day","💭"),w(29,"to travel","to go to other places","✈️"),
  w(29,"a jar","a glass pot you keep things in","🫙"),w(29,"a coin","round metal money","🪙"),
  w(29,"to save","to keep money for later","💰"),w(29,"to hope","to want something good to happen","🌟"),
  w(29,"would like to","a polite way to say 'want to'","🙂"),w(29,"one day","some time in the future","📅")])

add(n=30, slug="work", title="Opening up", sub="Say what you must do with have to.",
 story_h2="The early key", img1="a1s_30_early.png", alt1="Mia yawns as she opens the café shutters at dawn, keys in hand, street lamps still glowing.",
 img2="a1s_30_rules.png", alt2="Rosa kindly showing Mia how to stack cups safely behind the counter, both focused.",
 story_lines=["Big news! Rosa gives Mia the café <b>keys</b>. Now Mia can open the café. 🔑",
  "But it means an <b>early</b> start. Mia <b>has to</b> get up at six o'clock! 😴",
  "At the café, there is a lot to do. She <b>has to</b> turn on the machine.",
  "She <b>has to</b> clean the tables. She <b>has to</b> make the first coffee. ☕",
  '<span class=say>"You have to check the bread, too,"</span> says Rosa kindly.',
  "It is hard work. But Mia feels good. Rosa <b>trusts</b> her.",
  '<span class=say>"I have to work hard,"</span> says Mia, <span class=say>"but I love it!"</span> 💪'],
 tip1="we use <b>have to</b> for things that are necessary — jobs, rules. <i>I have to get up early.</i>",
 pat_h2="The pattern: <i>have to</i>", pat_build='            I <b>have to</b> get up early. (it is necessary)<br>\n            She <b>has to</b> clean the tables.<br>\n            Do you <b>have to</b> work on Sunday?\n',
 pat_tip="<b>Necessary?</b> use <i>have to / has to</i>. <i>He has to study. 📚</i>",
 yt_lead="Think about your day. Fill the gaps, then say them out loud.",
 yt_build='            In the morning, I have to <input class="blank" style="width:auto;display:inline-block" placeholder="get up / go to…">.<br><br>\n            At work, I have to <input class="blank" style="width:auto;display:inline-block" placeholder="…">.\n',
 yt_label="Write 3 things you have to do every week:", yt_ph="I have to …",
 checklist=["I can use <i>have to / has to</i>","I can talk about my jobs and rules","I can say what is necessary 💪","My new words are saved 🔁"],
 words=[w(30,"to open","to make ready for people to come in","🔓"),w(30,"early","before the usual time","🌅"),
  w(30,"a key","you open a door with it","🔑"),w(30,"have to","use this for necessary things","✅"),
  w(30,"to clean","to make something not dirty","🧹"),w(30,"to trust","to believe someone is good","🤝"),
  w(30,"a machine","it does a job for you","⚙️"),w(30,"hard work","when a job takes a lot of effort","💪")])

add(n=31, slug="birthday", title="Rosa's birthday", sub="Talk about dates: first, second, twenty-first.",
 story_h2="A secret plan", img1="a1s_31_calendar.png", alt1="Mia circles a day on a wall calendar with a red pencil, looking excited and secretive.",
 img2="a1s_31_birthday.png", alt2="Surprise! Rosa blows out candles on a cake as Mia, Tom and friends cheer, confetti in the air.",
 story_lines=["Mia has a secret. Rosa's <b>birthday</b> is on the <b>twenty-first</b> of May! 🎂",
  "Mia looks at the <b>calendar</b>. She circles the day with a red pencil.",
  '<span class=say>"When is it?"</span> asks Tom quietly. <span class=say>"The <b>first</b> Friday,"</span> whispers Mia.',
  "They plan a <b>surprise</b>. A cake, some flowers, and all Rosa's friends.",
  "On the twenty-first, Rosa comes to work. The café is dark. Then — SURPRISE! 🎉",
  "There is a big <b>cake</b> with candles. Everyone sings. Rosa cries happy tears.",
  '<span class=say>"This is the best birthday!"</span> she says. <span class=say>"Thank you all!"</span> 🎈'],
 tip1="for dates we use <b>ordinal numbers</b>: one → <b>first</b>, two → <b>second</b>, twenty-one → <b>twenty-first</b>.",
 pat_h2="The pattern: dates (ordinal numbers)", pat_build='            1 → <b>first</b> · 2 → <b>second</b> · 3 → <b>third</b> · 4 → <b>fourth</b><br>\n            21 → <b>twenty-first</b> · 30 → <b>thirtieth</b><br>\n            My birthday is <b>on the</b> tenth <b>of</b> June.\n',
 pat_tip="<b>Say the date:</b> the + ordinal + of + month. <i>the 3rd of March 📅.</i>",
 yt_lead="Think about important days. Fill the gaps, then say them out loud.",
 yt_build='            My birthday is on the <input class="blank" style="width:auto;display:inline-block" placeholder="first / tenth…"> of <input class="blank" style="width:auto;display:inline-block" placeholder="month">.<br><br>\n            Today is the <input class="blank" style="width:auto;display:inline-block" placeholder="…th"> of the month.\n',
 yt_label="Write 3 important dates for you:", yt_ph="… is on the …th of …",
 checklist=["I can say <i>first, second, third</i>","I can say a date","I can talk about birthdays 🎂","My new words are saved 🔁"],
 words=[w(31,"a birthday","the day you were born","🎂"),w(31,"a calendar","it shows the days and months","📅"),
  w(31,"a surprise","something nice you don't expect","🎉"),w(31,"first","number 1 in order","1️⃣"),
  w(31,"second","number 2 in order","2️⃣"),w(31,"a candle","a small light on a cake","🕯️"),
  w(31,"to sing","to make music with your voice","🎶"),w(31,"a cake","a sweet food for parties","🍰")])

add(n=32, slug="festival", title="The town festival", sub="Say when: in, on, at.",
 story_h2="Dancing in the square", img1="a1s_32_festival.png", alt1="The town square in festival mode: bunting, food stalls, a small brass band, families everywhere; Mia in the middle, delighted.",
 img2="a1s_32_dance.png", alt2="Mia dancing in the square with Tom and Rosa, lanterns glowing against an evening sky.",
 story_lines=["Once a year, the town has a big <b>festival</b>. It is <b>in</b> summer, <b>on</b> a Saturday. 🎪",
  "The <b>square</b> is full of colour. There is <b>bunting</b> and there are food stalls.",
  "A brass <b>band</b> plays. The music starts <b>at</b> six o'clock <b>in</b> the evening. 🎺",
  "Mia loves it. She eats sweet cakes and dances <b>in</b> the square.",
  "Tom and Rosa dance too! The <b>lanterns</b> glow in the dark sky. 🏮",
  '<span class=say>"I never dance,"</span> laughs Tom. <span class=say>"But tonight, I do!"</span>',
  "Late at night, the festival ends. <span class=say>\"What a day!\"</span> says Mia. ✨"],
 tip1="for time we use <b>in</b> (months, years, morning), <b>on</b> (days, dates), <b>at</b> (a clock time).",
 pat_h2="The pattern: <i>in / on / at</i> (time)", pat_build='            <b>in</b> summer · <b>in</b> May · <b>in</b> the evening (long times)<br>\n            <b>on</b> Saturday · <b>on</b> the 5th (days & dates)<br>\n            <b>at</b> six o\'clock · <b>at</b> night (clock times)\n',
 pat_tip="<b>Big to small:</b> in (year/month) → on (day) → at (time) 🕕.",
 yt_lead="Think about your week. Fill the gaps, then say them out loud.",
 yt_build='            I go to work <input class="blank" style="width:auto;display:inline-block" placeholder="in / on / at"> Monday.<br><br>\n            I get up <input class="blank" style="width:auto;display:inline-block" placeholder="in / on / at"> seven o\'clock.\n',
 yt_label="Write 3 sentences with in, on, or at:", yt_ph="I … on / in / at …",
 checklist=["I can use <i>in</i> for months","I can use <i>on</i> for days","I can use <i>at</i> for times 🕕","My new words are saved 🔁"],
 words=[w(32,"a festival","a big happy town party","🎪"),w(32,"a square","an open place in a town","🟦"),
  w(32,"a band","a group who play music","🎺"),w(32,"a lantern","a light in a paper cover","🏮"),
  w(32,"to dance","to move to music","💃"),w(32,"in","for months, years, and evenings","📆"),
  w(32,"on","for days and dates","🗓️"),w(32,"at","for clock times","🕕")])

add(n=33, slug="nextweek", title="Next week's plan", sub="Talk about the future with present continuous.",
 story_h2="A busy week ahead", img1="a1s_33_diary.png", alt1="Mia and Rosa look at a week planner on the café wall, pointing at different days.",
 img2="a1s_33_delivery.png", alt2="Mia shakes hands with a friendly delivery driver at the café door, crates of oranges beside them.",
 story_lines=["Mia keeps the café <b>diary</b>. Next week is very busy! 📔",
  '<span class=say>"On Monday, we\'re <b>meeting</b> the bread man,"</span> she tells Rosa.',
  '<span class=say>"On Tuesday, a school class is <b>coming</b> to visit."</span> 🎒',
  '<span class=say>"On Wednesday, we\'re <b>getting</b> a big <b>delivery</b> of oranges."</span> 🍊',
  '<span class=say>"And on Thursday, we\'re <b>having</b> a quiz night!"</span>',
  "Rosa smiles. <span class=say>\"You plan everything so well, Mia.\"</span>",
  "The delivery man comes. Mia checks the crates. Everything is ready. 📦"],
 tip1="we can use the <b>present continuous</b> (am/is/are + -ing) for plans in the future — with a future day or time.",
 pat_h2="The pattern: present continuous for the future", pat_build='            I\'m <b>meeting</b> the man <b>on Monday</b>.<br>\n            We\'re <b>getting</b> a delivery <b>tomorrow</b>.<br>\n            She\'s <b>coming</b> <b>next week</b>.\n',
 pat_tip="<b>A fixed plan?</b> use am/is/are + -ing + a future time. <i>I\'m seeing Tom tonight.</i>",
 yt_lead="Think about your week ahead. Fill the gaps, then say them out loud.",
 yt_build='            On <input class="blank" style="width:auto;display:inline-block" placeholder="day">, I\'m <input class="blank" style="width:auto;display:inline-block" placeholder="meeting / going / seeing…">.<br><br>\n            Tomorrow, I\'m <input class="blank" style="width:auto;display:inline-block" placeholder="…ing">.\n',
 yt_label="Write 3 plans for next week:", yt_ph="On … I'm …ing …",
 checklist=["I can talk about future plans","I can use am/is/are + -ing","I can plan my week 📔","My new words are saved 🔁"],
 words=[w(33,"a diary","a book for your plans and days","📔"),w(33,"a plan","what you are going to do","📝"),
  w(33,"a delivery","when goods are brought to you","📦"),w(33,"a class","a group who learn together","🎒"),
  w(33,"to meet","to come together with someone","🤝"),w(33,"next week","the week after this one","📅"),
  w(33,"to visit","to go and see a person or place","🏛️"),w(33,"ready","done and prepared","✅")])

add(n=34, slug="will", title="I think it'll rain", sub="Say what will happen: will.",
 story_h2="Grey clouds", img1="a1s_34_sky.png", alt1="Tom and Mia look up at big grey clouds over the town; Tom holds out a palm to feel for rain.",
 img2="a1s_34_promise.png", alt2="Mia and Rosa doing a pinky-promise across the café counter, both giggling.",
 story_lines=["Tonight is the outdoor cinema in the park. But the sky is grey. 🌥️",
  "Tom looks up. <span class=say>\"I think it <b>will</b> rain,\"</span> he says. <span class=say>\"Look at those clouds.\"</span>",
  '<span class=say>"Oh no,"</span> says Mia. <span class=say>"Then people <b>won\'t</b> come."</span>',
  '<span class=say>"Don\'t worry. I <b>\'ll</b> help you,"</span> says Tom. <span class=say>"I <b>\'ll</b> bring umbrellas."</span> ☂️',
  '<span class=say>"And I <b>\'ll</b> make hot chocolate,"</span> promises Rosa. They shake hands.',
  "At seven o'clock, it does not rain! The sky clears. The film starts. 🎬",
  '<span class=say>"You were wrong, Tom!"</span> laughs Mia. <span class=say>"A perfect night!"</span> 🌙'],
 tip1="we use <b>will</b> ('ll) for predictions (I think it will rain) and quick promises (I'll help you).",
 pat_h2="The pattern: <i>will</i>", pat_build='            I think it <b>will</b> rain. → it<b>\'ll</b> rain.<br>\n            People <b>won\'t</b> come. (will not)<br>\n            I <b>\'ll</b> help you. (a promise, decided now)\n',
 pat_tip="<b>Predict or promise:</b> use <i>\'ll</i>. <i>It\'ll be fine. I\'ll call you.</i>",
 yt_lead="Make some predictions and promises. Fill the gaps, then say them out loud.",
 yt_build='            I think tomorrow it <input class="blank" style="width:auto;display:inline-block" placeholder="will be / won\'t be…"> sunny.<br><br>\n            Don\'t worry, I\'ll <input class="blank" style="width:auto;display:inline-block" placeholder="help / bring / call…">.\n',
 yt_label="Write 3 sentences: what will happen tomorrow?", yt_ph="Tomorrow it will …",
 checklist=["I can use <i>will / \'ll</i>","I can use <i>won\'t</i>","I can make a prediction 🔮","My new words are saved 🔁"],
 words=[w(34,"a cloud","white or grey, it floats in the sky","☁️"),w(34,"will","use it for the future","🔮"),
  w(34,"won't","will not","🚫"),w(34,"to promise","to say you really will do it","🤞"),
  w(34,"to help","to do something good for someone","🤝"),w(34,"an umbrella","it keeps the rain off you","☂️"),
  w(34,"a film","a story you watch (a movie)","🎬"),w(34,"grey","the colour of rain clouds","🌫️")])

add(n=35, slug="because", title="Late!", sub="Ask and answer why with because.",
 story_h2="Why are you late?", img1="a1s_35_late.png", alt1="Mia runs down the street clutching a bag, scarf flying, clearly late; a bus pulls away behind her.",
 img2="a1s_35_explain.png", alt2="Mia at the café explaining with big hand gestures while Rosa laughs kindly, coffee pot in hand.",
 story_lines=["One morning, everything goes wrong for Mia. She is <b>late</b>! 🏃‍♀️",
  "First, her <b>alarm</b> doesn't ring. Then she can't find her keys. Then she misses the bus!",
  "She runs to the café. Rosa is there. <span class=say>\"<b>Why</b> are you late?\"</span> she asks.",
  '<span class=say>"I\'m late <b>because</b> my alarm didn\'t ring,"</span> says Mia, out of breath.',
  '<span class=say>"And <b>because</b> I lost my keys. And <b>because</b> I missed the bus!"</span>',
  "Rosa laughs kindly. <span class=say>\"What a morning! Sit down. Have a coffee.\"</span> ☕",
  '<span class=say>"Thank you,"</span> says Mia. <span class=say>"I need it!"</span> 😅'],
 tip1="we ask <b>Why…?</b> and answer with <b>because</b> + a reason. <i>Why? Because I was tired.</i>",
 pat_h2="The pattern: <i>why / because</i>", pat_build='            <b>Why</b> are you late? — <b>Because</b> I missed the bus.<br>\n            <b>Why</b> is Mia tired? — <b>Because</b> she worked all day.<br>\n            I\'m happy <b>because</b> it\'s sunny. ☀️\n',
 pat_tip="<b>Give a reason:</b> Why…? → Because… ↩️.",
 yt_lead="Give reasons for things. Fill the gaps, then say them out loud.",
 yt_build='            I\'m happy because <input class="blank" style="width:auto;display:inline-block" placeholder="it\'s sunny / I…">.<br><br>\n            I\'m tired because <input class="blank" style="width:auto;display:inline-block" placeholder="I…">.\n',
 yt_label="Write 3 sentences with because:", yt_ph="I … because …",
 checklist=["I can ask <i>Why…?</i>","I can answer with <i>because</i>","I can give reasons ↩️","My new words are saved 🔁"],
 words=[w(35,"late","after the right time","⏰"),w(35,"why","use it to ask the reason","❓"),
  w(35,"because","use it to give the reason","↩️"),w(35,"an alarm","it wakes you in the morning","⏰"),
  w(35,"to miss","to be too late for (a bus)","🚌"),w(35,"a reason","why something happens","💡"),
  w(35,"to run","to move very fast on your feet","🏃"),w(35,"tired","when you need to rest","😴")])

add(n=36, slug="walkclub", title="The walking club", sub="Ask about routines: How often…?",
 story_h2="Every Saturday", img1="a1s_36_walkclub.png", alt1="Mia and Tom in light rain jackets stride through the park with two cheerful elderly neighbours.",
 img2="a1s_36_chart.png", alt2="Mia proudly adds a star sticker to a little habit chart on her fridge.",
 story_lines=["Tom starts a walking <b>club</b>. <span class=say>\"Come with us, Mia!\"</span> he says. 🥾",
  '<span class=say>"<b>How often</b> do you walk?"</span> asks Mia. <span class=say>"<b>Every</b> Saturday,"</span> says Tom.',
  "Mia joins the club. Two kind neighbours come too. They walk through the park.",
  "Now Mia walks <b>twice</b> a week — with the club, and on her morning run. 🏞️",
  "She puts a little <b>chart</b> on her fridge. Every walk, she adds a gold star. ⭐",
  '<span class=say>"How often do you exercise?"</span> Rosa asks Mia. <span class=say>"Three times a week now!"</span>',
  "Mia feels strong and happy. And she has new friends, too. 😊"],
 tip1="we ask <b>How often…?</b> and answer with <i>every day, once a week, twice a month, three times a year</i>.",
 pat_h2="The pattern: <i>How often…?</i>", pat_build='            <b>How often</b> do you walk? — <b>Every</b> Saturday.<br>\n            <b>once</b> a week · <b>twice</b> a week · <b>three times</b> a week<br>\n            <b>every</b> day · <b>every</b> month\n',
 pat_tip="<b>How many times?</b> once, twice, three times… a week ⭐.",
 yt_lead="Think about your habits. Fill the gaps, then say them out loud.",
 yt_build='            I exercise <input class="blank" style="width:auto;display:inline-block" placeholder="once / twice / every day"> a week.<br><br>\n            I call my family <input class="blank" style="width:auto;display:inline-block" placeholder="every… / … times a…">.\n',
 yt_label="Write 3 sentences: how often do you do things?", yt_ph="I … once / twice / every …",
 checklist=["I can ask <i>How often…?</i>","I can say <i>once, twice, every…</i>","I can talk about my habits ⭐","My new words are saved 🔁"],
 words=[w(36,"a club","a group who do something together","🥾"),w(36,"how often","use it to ask about times","🔁"),
  w(36,"every","each one, with no gaps","💯"),w(36,"once","one time","1️⃣"),
  w(36,"twice","two times","2️⃣"),w(36,"a chart","a paper that shows your progress","📊"),
  w(36,"to exercise","to move your body to be healthy","🏃"),w(36,"a neighbour","a person who lives near you","🏡")])

add(n=37, slug="noise", title="Something in the night", sub="Talk about mystery: something, anything, nothing.",
 story_h2="A strange noise", img1="a1s_37_noise.png", alt1="Night: Mia sits up in bed wide-eyed, clutching the blanket; a strange shadow at the window; the ginger cat's fur puffed up.",
 img2="a1s_37_relief.png", alt2="Morning: Mia laughs with relief at a tree branch by her window; Tom peers over the fence holding pruning shears.",
 story_lines=["It is two o'clock in the night. Mia hears <b>something</b>! 😱",
  "Scratch, scratch, at the window. She sits up. Is there <b>anything</b> there?",
  "The ginger cat's fur goes up. Mia is <b>afraid</b>. <span class=say>\"Is <b>anybody</b> there?\"</span>",
  "She looks, but she sees <b>nothing</b> — only a dark <b>shadow</b>. She waits and waits.",
  "In the morning, she looks outside. There is <b>nothing</b> scary — just a tree <b>branch</b>! 🌳",
  "And Tom is in his garden with big scissors. <span class=say>\"Sorry! Did I wake you?\"</span> he laughs.",
  '<span class=say>"It was only a branch!"</span> says Mia, happy. <span class=say>"I was so silly!"</span> 😅'],
 tip1="<b>something</b>/<b>anything</b>/<b>nothing</b> for things · <b>somebody</b>/<b>anybody</b>/<b>nobody</b> for people.",
 pat_h2="The pattern: <i>something / anything / nothing</i>", pat_build='            I hear <b>something</b>. (+)<br>\n            Is there <b>anything</b>? (?) &nbsp;·&nbsp; I don\'t see <b>anything</b>. (−)<br>\n            There is <b>nothing</b> there. (= not anything)\n',
 pat_tip="<b>People:</b> somebody / anybody / nobody. <i>Is anybody there? Nobody.</i>",
 yt_lead="Answer about right now. Fill the gaps, then say them out loud.",
 yt_build='            There is <input class="blank" style="width:auto;display:inline-block" placeholder="something / nothing"> on my table.<br><br>\n            I can\'t hear <input class="blank" style="width:auto;display:inline-block" placeholder="anything / anybody">.\n',
 yt_label="Write 3 sentences with something/anything/nothing:", yt_ph="There is … / I can't see …",
 checklist=["I can use <i>something, anything</i>","I can use <i>nothing, nobody</i>","I can talk about things and people","My new words are saved 🔁"],
 words=[w(37,"a noise","a sound, often not nice","🔊"),w(37,"something","a thing (you don't say which)","❔"),
  w(37,"anything","a thing, in − and ? sentences","❓"),w(37,"nothing","not one thing","🚫"),
  w(37,"a shadow","a dark shape from a light","🌑"),w(37,"a branch","an arm of a tree","🌳"),
  w(37,"afraid","when you feel fear","😨"),w(37,"the night","the dark time to sleep","🌙")])

add(n=38, slug="storm", title="The night of the storm", sub="Say what was happening: past continuous.",
 story_h2="When the lights went out", img1="a1s_38_storm.png", alt1="A storm over the town at night: rain lashing the streets, one warm candle-lit café window glowing.",
 img2="a1s_38_candles.png", alt2="Inside the café during the power cut: Mia, Tom and Rosa playing cards by candlelight.",
 story_lines=["One evening, a big <b>storm</b> comes. The wind is loud. The rain is heavy. ⛈️",
  "Mia and her friends are in the café. They <b>were talking</b> and laughing.",
  "Then — click! The lights go out! The <b>power</b> is gone. Everything is dark.",
  '<span class=say>"What <b>were</b> you <b>doing</b>?"</span> laughs Tom. <span class=say>"I <b>was making</b> coffee!"</span> says Rosa.',
  "Rosa finds <b>candles</b>. Soon the café is warm and golden. 🕯️",
  "They play <b>cards</b> by candlelight while the storm shakes the windows.",
  '<span class=say>"This is nice,"</span> smiles Mia. <span class=say>"A storm outside, and friends inside."</span> ❤️'],
 tip1="the <b>past continuous</b> (was/were + -ing) says what was happening at a moment in the past.",
 pat_h2="The pattern: past continuous", pat_build='            I <b>was making</b> coffee.<br>\n            They <b>were playing</b> cards.<br>\n            What <b>were</b> you <b>doing</b> when the lights went out?\n',
 pat_tip="<b>In the middle of a past action?</b> was/were + -ing. <i>I was sleeping at ten.</i>",
 yt_lead="Think about yesterday. Fill the gaps, then say them out loud.",
 yt_build='            At eight o\'clock last night, I was <input class="blank" style="width:auto;display:inline-block" placeholder="watching / eating…">.<br><br>\n            My family were <input class="blank" style="width:auto;display:inline-block" placeholder="…ing">.\n',
 yt_label="Write 3 sentences: what were you doing yesterday?", yt_ph="At … I was …ing",
 checklist=["I can use <i>was/were + -ing</i>","I can say what was happening","I can tell a past story ⛈️","My new words are saved 🔁"],
 words=[w(38,"a storm","strong wind and heavy rain","⛈️"),w(38,"the power","the electricity for lights","💡"),
  w(38,"a candle","it gives light with a small flame","🕯️"),w(38,"cards","you play games with them","🃏"),
  w(38,"the wind","fast-moving air","💨"),w(38,"dark","with no light","🌑"),
  w(38,"was doing","use it for past actions in progress","⏳"),w(38,"golden","warm yellow like gold","🌟")])

add(n=39, slug="sick", title="Mia has a cold", sub="Give advice: should / shouldn't.",
 story_h2="Get well soon", img1="a1s_39_sick.png", alt1="Mia on her sofa wrapped in a blanket with a red nose, tissues and lemon tea; the ginger cat sits beside her like a nurse.",
 img2="a1s_39_soup.png", alt2="Rosa arriving at Mia's door with a pot of soup; Tom behind her holding flowers.",
 story_lines=["Oh no. Mia is <b>ill</b>. She has a bad <b>cold</b>. Her nose is red. 🤧",
  "She stays on the sofa with a blanket. The ginger cat sits with her, like a little nurse.",
  "Rosa calls. <span class=say>\"You <b>should</b> stay in bed,\"</span> she says. <span class=say>\"You <b>shouldn\'t</b> come to work.\"</span>",
  '<span class=say>"You should drink hot <b>tea</b> with lemon,"</span> says Tom. <span class=say>"And rest a lot."</span> 🍋',
  "Soon there is a knock. Rosa brings <b>soup</b>! Tom brings flowers. 💐",
  '<span class=say>"You shouldn\'t worry about the café,"</span> says Rosa. <span class=say>"Just get <b>better</b>."</span>',
  "Mia feels warm inside. <span class=say>\"With friends like you, I\'ll be fine!\"</span> 😊"],
 tip1="we use <b>should</b> for good advice and <b>shouldn't</b> for a bad idea. <i>You should rest.</i>",
 pat_h2="The pattern: <i>should / shouldn't</i>", pat_build='            You <b>should</b> rest. (good idea 👍)<br>\n            You <b>shouldn\'t</b> go to work. (bad idea 👎)<br>\n            <b>Should</b> I call a doctor?\n',
 pat_tip="<b>Advice:</b> should 👍 · shouldn\'t 👎. <i>You should sleep. You shouldn\'t worry.</i>",
 yt_lead="Give advice to a tired friend. Fill the gaps, then say them out loud.",
 yt_build='            You should <input class="blank" style="width:auto;display:inline-block" placeholder="rest / drink / sleep…">.<br><br>\n            You shouldn\'t <input class="blank" style="width:auto;display:inline-block" placeholder="…">.\n',
 yt_label="Write 3 pieces of advice (should / shouldn't):", yt_ph="You should / shouldn't …",
 checklist=["I can use <i>should</i> for advice","I can use <i>shouldn\'t</i>","I can help a sick friend 💐","My new words are saved 🔁"],
 words=[w(39,"ill","not well; sick","🤒"),w(39,"a cold","an illness with a runny nose","🤧"),
  w(39,"should","use it to give good advice","👍"),w(39,"shouldn't","use it for a bad idea","👎"),
  w(39,"soup","a warm liquid food","🍲"),w(39,"to rest","to stop and relax","🛌"),
  w(39,"better","more well than before","💪"),w(39,"a doctor","they help you when you are ill","🩺")])

add(n=40, slug="inspection", title="The inspection", sub="Say what is not allowed: must / mustn't.",
 story_h2="Everything must be perfect", img1="a1s_40_inspect.png", alt1="A very neat café: Rosa straightening chairs while Mia polishes the counter; a clipboard with tick marks lies on the bar.",
 img2="a1s_40_pass.png", alt2="Rosa and Mia high-fiving behind the counter, a little prize rosette pinned by the till.",
 story_lines=["Today the café has an <b>inspection</b>. A person comes to check the rules. 📋",
  "Rosa is a little <b>nervous</b>. <span class=say>\"Everything <b>must</b> be perfect,\"</span> she says.",
  '<span class=say>"We <b>must</b> clean every table,"</span> says Mia. <span class=say>"And we <b>mustn\'t</b> forget the kitchen!"</span>',
  "They work hard. The counter <b>shines</b>. The floor is spotless. ✨",
  "The inspector comes in. She looks at everything and writes on her <b>clipboard</b>.",
  '<span class=say>"Very good,"</span> she says at last. <span class=say>"You <b>pass</b>!"</span> 🎉',
  "Rosa and Mia high-five. <span class=say>\"We did it together!\"</span> laughs Mia. 🏅"],
 tip1="<b>must</b> = it is very important to do it. <b>mustn't</b> = it is not allowed, don't do it!",
 pat_h2="The pattern: <i>must / mustn't</i>", pat_build='            Everything <b>must</b> be clean. (very important)<br>\n            You <b>mustn\'t</b> forget the kitchen. (not allowed!)<br>\n            We <b>must</b> pass this inspection.\n',
 pat_tip="<b>must</b> = do it! ✅ · <b>mustn\'t</b> = don\'t! 🚫 <i>You mustn\'t be late.</i>",
 yt_lead="Think of important rules. Fill the gaps, then say them out loud.",
 yt_build='            At my work, we must <input class="blank" style="width:auto;display:inline-block" placeholder="be… / clean…">.<br><br>\n            We mustn\'t <input class="blank" style="width:auto;display:inline-block" placeholder="…">.\n',
 yt_label="Write 3 rules with must / mustn't:", yt_ph="You must / mustn't …",
 checklist=["I can use <i>must</i>","I can use <i>mustn\'t</i>","I can talk about rules 📋","My new words are saved 🔁"],
 words=[w(40,"an inspection","a check to see all is correct","📋"),w(40,"a rule","something you must do or not do","📏"),
  w(40,"must","use it for very important things","✅"),w(40,"mustn't","use it for things not allowed","🚫"),
  w(40,"nervous","a little afraid before something","😰"),w(40,"to shine","to be very bright and clean","✨"),
  w(40,"to pass","to be good enough; to succeed","🎉"),w(40,"a clipboard","a board to hold papers","📋")])

add(n=41, slug="scarf", title="Whose scarf is this?", sub="Say who owns it: whose and 's.",
 story_h2="Lost property", img1="a1s_41_scarf.png", alt1="Mia holds up a red scarf in the middle of the café, asking the room; customers pat their necks comically.",
 img2="a1s_41_owner.png", alt2="An old lady joyfully claims the red scarf and pats Mia's hand; Tom applauds gently.",
 story_lines=["Mia finds a beautiful red <b>scarf</b> on a café chair. But <b>whose</b> is it? 🧣",
  "She holds it up. <span class=say>\"<b>Whose</b> scarf is this?\"</span> she asks the room.",
  "Everyone checks their neck! <span class=say>\"It isn\'t <b>mine</b>,\"</span> says one man.",
  '<span class=say>"Is it <b>Rosa\'s</b>?"</span> asks Tom. <span class=say>"No, <b>Rosa\'s</b> scarf is blue,"</span> says Mia.',
  "Then an old lady comes in. <span class=say>\"Oh! That\'s <b>mine</b>! It\'s the <b>lady\'s</b> scarf!\"</span> 😊",
  "She is so happy. <span class=say>\"Thank you! My daughter made it for me.\"</span>",
  "Mia smiles. <span class=say>\"I\'m glad it\'s <b>yours</b> again!\"</span> 🧣"],
 tip1="we ask <b>Whose…?</b> for the owner. To answer, we add <b>'s</b> to a name: <i>Rosa's scarf</i>.",
 pat_h2="The pattern: <i>whose</i> and <i>'s</i>", pat_build='            <b>Whose</b> scarf is this? — It\'s <b>Rosa\'s</b>.<br>\n            It\'s the <b>lady\'s</b> scarf. (the scarf of the lady)<br>\n            It\'s <b>mine</b> · <b>yours</b> · <b>hers</b> · <b>his</b>.\n',
 pat_tip="<b>Who owns it?</b> add <i>\'s</i> to the name: <i>Tom\'s cup · Mia\'s bag.</i>",
 yt_lead="Think about your things and people. Fill the gaps, then say them out loud.",
 yt_build='            This is my <input class="blank" style="width:auto;display:inline-block" placeholder="phone / bag…">. It\'s <b>mine</b>.<br><br>\n            That is my friend\'s. It\'s <input class="blank" style="width:auto;display:inline-block" placeholder="hers / his / theirs">.\n',
 yt_label="Write 3 sentences with 's or mine/yours:", yt_ph="It's …'s / It's mine",
 checklist=["I can ask <i>Whose…?</i>","I can add <i>\'s</i> to say who owns it","I can use <i>mine, yours, hers</i>","My new words are saved 🔁"],
 words=[w(41,"a scarf","you wear it around your neck","🧣"),w(41,"whose","use it to ask who owns something","❓"),
  w(41,"mine","it belongs to me","🙋"),w(41,"yours","it belongs to you","👉"),
  w(41,"hers","it belongs to her","👩"),w(41,"an owner","the person a thing belongs to","🔑"),
  w(41,"a lady","a polite word for a woman","👵"),w(41,"to find","to see something you looked for","🔎")])

add(n=42, slug="gift", title="The perfect gift", sub="Choose things: one, ones.",
 story_h2="This one or that one?", img1="a1s_42_gift.png", alt1="Mia in a little gift shop choosing between two teapots — a plain one and a flowery one — the shopkeeper waiting patiently.",
 img2="a1s_42_wrap.png", alt2="Mia wrapping the flowery teapot in amber paper with a big ribbon at her kitchen table.",
 story_lines=["Mia wants to buy a <b>gift</b> for Rosa, to say thank you. She goes to a little shop. 🎁",
  "She sees two teapots. A plain white <b>one</b> and a lovely flowery <b>one</b>. 🫖",
  '<span class=say>"Which <b>one</b> is better?"</span> she asks the shopkeeper. <span class=say>"The flowery one is nicer,"</span> he says.',
  "She looks at some cups too. <span class=say>\"I like the blue <b>ones</b>,\"</span> she says.",
  "In the end, Mia chooses the flowery teapot. <span class=say>\"This <b>one</b>, please!\"</span>",
  "At home, she <b>wraps</b> it in amber paper with a big <b>ribbon</b>. 🎀",
  '<span class=say>"Rosa will love this one,"</span> she smiles. 😊'],
 tip1="we say <b>one</b> for a single thing and <b>ones</b> for more — so we don't repeat the noun.",
 pat_h2="The pattern: <i>one / ones</i>", pat_build='            Which teapot? — The flowery <b>one</b>. (= teapot)<br>\n            I like the blue <b>ones</b>. (= cups)<br>\n            This <b>one</b>, please! · Not that <b>one</b>.\n',
 pat_tip="<b>Don\'t repeat the noun:</b> the red one · the small ones 🔵.",
 yt_lead="Imagine you are shopping. Fill the gaps, then say them out loud.",
 yt_build='            I like the <input class="blank" style="width:auto;display:inline-block" placeholder="blue / big…"> one.<br><br>\n            I don\'t like the <input class="blank" style="width:auto;display:inline-block" placeholder="…"> ones.\n',
 yt_label="Write 3 sentences with one or ones:", yt_ph="I like the … one / ones",
 checklist=["I can use <i>one</i> for one thing","I can use <i>ones</i> for more","I can choose a gift 🎁","My new words are saved 🔁"],
 words=[w(42,"a gift","a present you give someone","🎁"),w(42,"one","use it so you don't repeat the noun","1️⃣"),
  w(42,"ones","'one' for more than one thing","🔢"),w(42,"to wrap","to cover a gift in paper","🎁"),
  w(42,"a ribbon","a pretty strip to tie a gift","🎀"),w(42,"to choose","to pick the one you want","👉"),
  w(42,"a shop","you buy things here","🏬"),w(42,"plain","simple, with no pattern","⬜")])

add(n=43, slug="ever", title="Have you ever…?", sub="Talk about your life: present perfect.",
 story_h2="Tom's stories", img1="a1s_43_stories.png", alt1="Tom telling a story at the café, arms spread wide like a fisherman describing a giant catch; Mia and Rosa enthralled.",
 img2="a1s_43_treasures.png", alt2="Tom's old travel keepsakes on the table: a compass, seashells, an old photograph, a folded map.",
 story_lines=["Tom loves to tell <b>stories</b> from his life. He has <b>travelled</b> a lot. 🌍",
  '<span class=say>"<b>Have</b> you <b>ever seen</b> the sea at midnight?"</span> he asks Mia.',
  '<span class=say>"No, I <b>haven\'t</b>,"</span> she says. <span class=say>"<b>Have</b> you?"</span> <span class=say>"Yes, I <b>have</b>!"</span> smiles Tom.',
  '<span class=say>"I\'ve <b>climbed</b> a mountain. I\'ve <b>eaten</b> strange food. I\'ve <b>met</b> kings!"</span> 👑',
  "He shows his <b>treasures</b>: a compass, some shells, an old photo. 🧭",
  '<span class=say>"<b>Have</b> you <b>ever been</b> to the sea?"</span> he asks. <span class=say>"Yes, once!"</span> says Mia.',
  '<span class=say>"Life is short,"</span> says Tom. <span class=say>"Do many things!"</span> ✨'],
 tip1="<b>Have you ever…?</b> asks about your life (any time). We use <i>have</i> + the third form: seen, been, eaten.",
 pat_h2="The pattern: <i>Have you ever…?</i>", pat_build='            <b>Have</b> you <b>ever seen</b> the sea? — Yes, I <b>have</b>. / No, I <b>haven\'t</b>.<br>\n            I <b>\'ve been</b> to Paris. · I <b>\'ve eaten</b> sushi.<br>\n            see→<b>seen</b> · go→<b>been</b> · eat→<b>eaten</b>\n',
 pat_tip="<b>Any time in your life?</b> Have you ever…? <i>Have you ever flown? 🛫</i>",
 yt_lead="Think about your life. Fill the gaps, then say them out loud.",
 yt_build='            Have you ever <input class="blank" style="width:auto;display:inline-block" placeholder="seen / eaten / been…"> …?<br><br>\n            I have <input class="blank" style="width:auto;display:inline-block" placeholder="been to / eaten…">.\n',
 yt_label="Write 3 'Have you ever…?' questions:", yt_ph="Have you ever …?",
 checklist=["I can ask <i>Have you ever…?</i>","I can answer <i>Yes I have / No I haven\'t</i>","I can talk about my life ✨","My new words are saved 🔁"],
 words=[w(43,"a story","a tale someone tells you","📖"),w(43,"to travel","to go to other places","🌍"),
  w(43,"ever","at any time in your life","♾️"),w(43,"a treasure","a special thing you keep","💎"),
  w(43,"a compass","it shows you north and south","🧭"),w(43,"seen","the third form of 'see'","👀"),
  w(43,"been","the third form of 'be/go'","📍"),w(43,"short","not long","📏")])

add(n=44, slug="gone", title="Where's Rosa?", sub="Say been vs gone.",
 story_h2="The closed café", img1="a1s_44_closed.png", alt1="Mia outside the café looking puzzled: the lights are off and a small blank sign hangs on the door.",
 img2="a1s_44_postcard.png", alt2="Mia reading a colourful postcard with palm trees on it, smiling with relief.",
 story_lines=["One morning, Mia comes to work. But the café is dark and <b>closed</b>! 😮",
  "There is a small sign on the door. <span class=say>\"Where is Rosa?\"</span> Mia thinks.",
  "She calls Tom. <span class=say>\"Rosa has <b>gone</b> to the city,\"</span> he says. <span class=say>\"She isn\'t back yet.\"</span>",
  '<span class=say>"Why?"</span> asks Mia. <span class=say>"For her sister\'s wedding. She\'ll be back on Monday."</span> 💒',
  "Two days later, a <b>postcard</b> comes. It has palm trees on it! 🌴",
  '<span class=say>"I have <b>been</b> to a beautiful city,"</span> Rosa writes. <span class=say>"I\'m coming home soon!"</span>',
  "On Monday, Rosa is back. <span class=say>\"I have gone and I have come home!\"</span> she laughs. 😊"],
 tip1="<b>has gone</b> = she left and is still away. <b>has been</b> = she went and is back now.",
 pat_h2="The pattern: <i>been / gone</i>", pat_build='            Rosa has <b>gone</b> to the city. (still away 🚗→)<br>\n            Rosa has <b>been</b> to the city. (and is back now 🏠)<br>\n            I\'ve <b>been</b> there. · He\'s <b>gone</b> home.\n',
 pat_tip="<b>gone</b> = away now · <b>been</b> = went and came back 🔁.",
 yt_lead="Think about people you know. Fill the gaps, then say them out loud.",
 yt_build='            My friend has <input class="blank" style="width:auto;display:inline-block" placeholder="gone / been"> to work. (still there)<br><br>\n            I have <input class="blank" style="width:auto;display:inline-block" placeholder="been"> to the shop. (I\'m back)\n',
 yt_label="Write 2 sentences with been and 1 with gone:", yt_ph="I have been to … / … has gone to …",
 checklist=["I can use <i>has gone</i> (still away)","I can use <i>has been</i> (and back)","I can explain where people are","My new words are saved 🔁"],
 words=[w(44,"closed","not open","🔒"),w(44,"a sign","words on a board that tell you something","🪧"),
  w(44,"gone","left and still away","🚗"),w(44,"been","went and came back","🔁"),
  w(44,"a postcard","a card you send from a trip","📬"),w(44,"a wedding","the day two people marry","💒"),
  w(44,"a city","a very big town","🏙️"),w(44,"soon","in a short time","⏳")])

add(n=45, slug="ifitrains", title="If it rains…", sub="Make plans with conditions: if + will.",
 story_h2="Rain or shine", img1="a1s_45_plan.png", alt1="Mia, Tom and Rosa around a table planning a street party: paper plans, bunting samples, thumbs up all round.",
 img2="a1s_45_weather.png", alt2="Mia at the café door looking up at a half-sunny, half-cloudy sky, an armful of bunting ready.",
 story_lines=["The town is planning a big street party! Mia, Tom and Rosa make a plan. 🎉",
  "But the weather is not sure. Half sun, half cloud. What will they do?",
  '<span class=say>"<b>If</b> it <b>rains</b>, we <b>\'ll move</b> inside,"</span> says Rosa. <span class=say>"The café is big enough."</span>',
  '<span class=say>"And <b>if</b> it <b>\'s sunny</b>, we <b>\'ll dance</b> in the street!"</span> says Mia. 💃',
  '<span class=say>"<b>If</b> people <b>come</b>, we <b>\'ll need</b> lots of cake,"</span> laughs Tom.',
  "They put up bunting and hope for sun. Mia looks at the sky. ☀️🌥️",
  '<span class=say>"Rain or sun, it <b>\'ll be</b> a good party!"</span> she says. 🎈'],
 tip1="to plan with a condition: <b>if</b> + present, then <b>will</b>. <i>If it rains, we'll go inside.</i>",
 pat_h2="The pattern: <i>if + will</i> (first conditional)", pat_build='            <b>If</b> it <b>rains</b>, we <b>\'ll</b> go inside.<br>\n            <b>If</b> it <b>\'s</b> sunny, we <b>\'ll</b> dance outside.<br>\n            <b>If</b> you <b>come</b>, I <b>\'ll</b> be happy.\n',
 pat_tip="<b>Condition → result:</b> If + now, will + future. ☔→🏠.",
 yt_lead="Make plans for tomorrow. Fill the gaps, then say them out loud.",
 yt_build='            If it rains tomorrow, I\'ll <input class="blank" style="width:auto;display:inline-block" placeholder="stay / read…">.<br><br>\n            If it\'s sunny, I\'ll <input class="blank" style="width:auto;display:inline-block" placeholder="…">.\n',
 yt_label="Write 3 sentences with 'if … I'll …':", yt_ph="If …, I'll …",
 checklist=["I can use <i>if + present</i>","I can add <i>will</i> for the result","I can plan for the weather ☔","My new words are saved 🔁"],
 words=[w(45,"if","use it to talk about a condition","❔"),w(45,"a street","a road with houses and shops","🛣️"),
  w(45,"bunting","little flags on a string for parties","🎊"),w(45,"to move","to go to another place","➡️"),
  w(45,"inside","not outside; in a building","🏠"),w(45,"enough","as much as you need","👌"),
  w(45,"to need","to have to have something","🙏"),w(45,"sunny","with lots of sun","☀️")])

add(n=46, slug="race", title="The sack race", sub="Compare with as … as.",
 story_h2="Neck and neck", img1="a1s_46_race.png", alt1="A friendly sack race in the park: Mia and Tom neck-and-neck mid-hop, Rosa laughing as referee with a whistle.",
 img2="a1s_46_tie.png", alt2="Mia and Tom collapsed on the grass laughing, holding one small ribbon between them.",
 story_lines=["It is games day in the park! There is a funny <b>sack race</b>. 🏃",
  "Mia and Tom both jump in big sacks. Rosa is the <b>referee</b> with a <b>whistle</b>.",
  '<span class=say>"Ready? Go!"</span> They hop and hop. Mia is fast — but Tom is <b>as fast as</b> Mia!',
  "They jump side by side. Tom is not <b>as young as</b> Mia, but he is strong! 💪",
  "At the <b>finish</b>, they cross the line together. It is a <b>tie</b>! 🎀",
  "They fall on the grass, laughing. <span class=say>\"You\'re <b>as good as</b> me!\"</span> says Mia.",
  '<span class=say>"We\'re both winners!"</span> laughs Tom. They share the little ribbon. 🏅'],
 tip1="to say two things are the same, we use <b>as … as</b>. <i>Tom is as fast as Mia.</i> Not the same: <i>not as … as</i>.",
 pat_h2="The pattern: <i>as … as</i>", pat_build='            Tom is <b>as fast as</b> Mia. (the same speed)<br>\n            Tom is <b>not as young as</b> Mia. (Mia is younger)<br>\n            This café is <b>as good as</b> that one.\n',
 pat_tip="<b>The same?</b> as … as. <b>Not the same?</b> not as … as. ⚖️",
 yt_lead="Compare things that are the same or different. Fill the gaps, then say them out loud.",
 yt_build='            My town is <input class="blank" style="width:auto;display:inline-block" placeholder="as big as / not as big as"> yours.<br><br>\n            I am <input class="blank" style="width:auto;display:inline-block" placeholder="as … as / not as … as"> my friend.\n',
 yt_label="Write 3 sentences with as … as:", yt_ph="… is (not) as … as …",
 checklist=["I can use <i>as … as</i>","I can use <i>not as … as</i>","I can compare two things ⚖️","My new words are saved 🔁"],
 words=[w(46,"a race","who can be fastest?","🏁"),w(46,"a referee","the person who runs a game","👨‍⚖️"),
  w(46,"a whistle","you blow it to make a sound","🎽"),w(46,"to jump","to push up off the ground","⬆️"),
  w(46,"the finish","the end of a race","🏁"),w(46,"a tie","when two people are equal","🤝"),
  w(46,"as … as","use it to say things are the same","⚖️"),w(46,"a winner","the person who wins","🏆")])

add(n=47, slug="toomuch", title="Too much lemonade", sub="Say how much: too much, too many, enough.",
 story_h2="Party shopping", img1="a1s_47_shopping.png", alt1="Mia carrying a comic tower of party supplies — cups, streamers, a piñata — wobbling slightly down the street.",
 img2="a1s_47_check.png", alt2="Rosa counting a mountain of cups on the counter with a raised eyebrow; Mia grins sheepishly.",
 story_lines=["It is the day before the party. Mia goes shopping for it. 🎉",
  "But she buys <b>too many</b> cups — two hundred! And <b>too much</b> lemonade! 🥤",
  "She buys streamers, balloons, and one big <b>piñata</b>. The bags are so heavy!",
  "Back at the café, Rosa counts everything. <span class=say>\"Mia! This is <b>too much</b>!\"</span> she laughs.",
  '<span class=say>"But we don\'t have <b>enough</b> chairs,"</span> says Mia. <span class=say>"Oops!"</span> 🪑',
  '<span class=say>"Too many cups, not <b>enough</b> chairs,"</span> smiles Rosa. <span class=say>"Perfect!"</span>',
  '<span class=say>"Well,"</span> laughs Mia, <span class=say>"nobody will be thirsty!"</span> 😄'],
 tip1="<b>too much</b> + can't-count (lemonade) · <b>too many</b> + can-count (cups) · <b>enough</b> = the right amount.",
 pat_h2="The pattern: <i>too much / too many / enough</i>", pat_build='            <b>too much</b> lemonade (can\'t count) · <b>too many</b> cups (can count)<br>\n            not <b>enough</b> chairs (we need more)<br>\n            We have <b>enough</b> food. (just right 👍)\n',
 pat_tip="<b>too many</b> 🥤🥤🥤 = more than you need · <b>enough</b> = just right 👌.",
 yt_lead="Think about what you have. Fill the gaps, then say them out loud.",
 yt_build='            I have too <input class="blank" style="width:auto;display:inline-block" placeholder="much / many"> homework.<br><br>\n            I don\'t have <input class="blank" style="width:auto;display:inline-block" placeholder="enough"> time.\n',
 yt_label="Write 3 sentences with too much/many or enough:", yt_ph="too much/many … / enough …",
 checklist=["I can use <i>too much / too many</i>","I can use <i>enough</i>","I can talk about amounts 🥤","My new words are saved 🔁"],
 words=[w(47,"too much","more than you need (can't count)","🥤"),w(47,"too many","more than you need (can count)","🔢"),
  w(47,"enough","the right amount","👌"),w(47,"lemonade","a sweet cold drink","🥤"),
  w(47,"a balloon","you blow air into it for parties","🎈"),w(47,"a chair","you sit on it","🪑"),
  w(47,"heavy","hard to carry; not light","🏋️"),w(47,"thirsty","when you want a drink","💧")])

add(n=48, slug="quiz", title="Quiz night", sub="Describe with who and which.",
 story_h2="A tricky question", img1="a1s_48_quiz.png", alt1="Quiz night at the café: teams at tables, Tom as quizmaster holding little cards, warm lamplight.",
 img2="a1s_48_win.png", alt2="Mia's team celebrating with a tiny trophy; Rosa arrives with a celebratory tray of hot chocolates.",
 story_lines=["Thursday is <b>quiz</b> night! The café is full. Tom is the <b>quizmaster</b>. 🎤",
  "Mia's <b>team</b> is Rosa, Mia and a friendly neighbour. They want to win!",
  '<span class=say>"Question one,"</span> says Tom. <span class=say>"He was a king <b>who</b> lost his head. Who was he?"</span> 👑',
  '<span class=say>"Question two: it is a fruit <b>which</b> is long and yellow."</span> <span class=say>"A banana!"</span> shouts Rosa. 🍌',
  '<span class=say>"Question three: she is a woman <b>who</b> flew across the sea."</span>',
  "Mia's team thinks hard. They know many <b>answers</b>! ✍️",
  "At the end, Tom counts. <span class=say>\"The winners are... Mia\'s team!\"</span> 🏆 They cheer!"],
 tip1="we use <b>who</b> for people and <b>which</b> for things, to give more information. <i>a king who… · a fruit which…</i>",
 pat_h2="The pattern: <i>who / which</i>", pat_build='            a king <b>who</b> lost his head (people → who)<br>\n            a fruit <b>which</b> is yellow (things → which)<br>\n            the woman <b>who</b> flew · the machine <b>which</b> flies\n',
 pat_tip="<b>People → who 👤 · Things → which 📦.</b>",
 yt_lead="Describe people and things. Fill the gaps, then say them out loud.",
 yt_build='            A teacher is a person <input class="blank" style="width:auto;display:inline-block" placeholder="who"> helps you learn.<br><br>\n            A fridge is a thing <input class="blank" style="width:auto;display:inline-block" placeholder="which"> keeps food cold.\n',
 yt_label="Write 3 sentences with who or which:", yt_ph="A … is a person/thing who/which …",
 checklist=["I can use <i>who</i> for people","I can use <i>which</i> for things","I can describe people and things","My new words are saved 🔁"],
 words=[w(48,"a quiz","a game of questions","❓"),w(48,"a team","a group who play together","👥"),
  w(48,"who","use it to describe people","👤"),w(48,"which","use it to describe things","📦"),
  w(48,"an answer","what you say to a question","💬"),w(48,"a question","something you ask","❔"),
  w(48,"to win","to be the best in a game","🏆"),w(48,"a prize","what you get for winning","🥇")])

add(n=49, slug="year", title="One whole year", sub="Tell a story in order: first, then, finally.",
 story_h2="Mia's scrapbook", img1="a1s_49_album.png", alt1="Mia sticking photos into a scrapbook at her table, remembering; the ginger cat asleep on her lap.",
 img2="a1s_49_memories.png", alt2="A warm collage: memory bubbles around Mia — the suitcase arrival, the café counter, the umbrella, the wonky cake, the castle.",
 story_lines=["It is almost one year since Mia came to the town. She makes a <b>scrapbook</b>. 📔",
  "She sticks in her photos and <b>remembers</b> everything, in order.",
  '<span class=say>"<b>First</b>, I arrived with one suitcase,"</span> she says. <span class=say>"I knew nobody."</span> 🧳',
  '<span class=say>"<b>Then</b> I met Tom, and Rosa gave me a job at the café."</span> ☕',
  '<span class=say>"<b>After that</b>, I learned to bake, I got my little flat, and Ana came to visit."</span>',
  '<span class=say>"And <b>finally</b>, this town became my home,"</span> she smiles. 🏡',
  "Good news! Ana is coming back — for a big party. <span class=say>\"What a year!\"</span> says Mia. ✨"],
 tip1="to tell a story in order, we use <b>first</b>, <b>then</b>, <b>after that</b>, and <b>finally</b>.",
 pat_h2="The pattern: sequencers", pat_build='            <b>First</b>, I arrived. →<br>\n            <b>Then</b> I met Tom. → <b>After that</b>, I got a job.<br>\n            <b>Finally</b>, this became my home.\n',
 pat_tip="<b>In order:</b> First → Then → After that → Finally. 1️⃣2️⃣3️⃣4️⃣",
 yt_lead="Tell your own day or year in order. Fill the gaps, then say them out loud.",
 yt_build='            First, I <input class="blank" style="width:auto;display:inline-block" placeholder="woke up / …">.<br><br>\n            Then I <input class="blank" style="width:auto;display:inline-block" placeholder="…">. Finally, I <input class="blank" style="width:auto;display:inline-block" placeholder="…">.\n',
 yt_label="Write your day in order (first, then, finally):", yt_ph="First … Then … Finally …",
 checklist=["I can use <i>first, then</i>","I can use <i>after that, finally</i>","I can tell a story in order 📔","My new words are saved 🔁"],
 words=[w(49,"a scrapbook","a book for your photos and memories","📔"),w(49,"to remember","to keep something in your mind","🧠"),
  w(49,"first","before everything else","1️⃣"),w(49,"then","after that","➡️"),
  w(49,"finally","at the end, last of all","🏁"),w(49,"a memory","a thing you remember","💭"),
  w(49,"a year","twelve months","📅"),w(49,"home","the place where you belong","🏡")])

add(n=50, slug="home", title="This is home", sub="A big review — and Mia's speech.",
 story_h2="The street party", img1="a1s_50_party.png", alt1="The street party outside the café: long tables, lanterns, the whole town; Mia at the centre between Tom, Rosa and Ana, raising glasses of lemonade.",
 img2="a1s_50_speech.png", alt2="Mia standing on a chair giving a happy little speech, hand on heart, friends cheering around her in the evening glow.",
 story_lines=["The big day is here — the street <b>party</b>! The whole town comes. 🎉",
  "There are long tables, <b>lanterns</b>, music, and lots of cake. Ana is back, too! 🎈",
  "Rosa, Tom, Ana and all Mia's friends are here. Everyone is smiling.",
  "Then Mia stands on a chair. She wants to say something — in English. 🗣️",
  '<span class=say>"One year ago, I <b>arrived</b> with one suitcase. I knew nobody,"</span> she says.',
  '<span class=say>"Now I have a home, a job, and the best friends. Thank you, all of you."</span> ❤️',
  "Everyone cheers. Mia looks around at her town. <span class=say>\"This,\"</span> she says softly, <span class=say>\"is home.\"</span> 🏡✨"],
 tip1="today is a review! You know so much now — words, patterns, and Mia's whole story. Be proud! 🎉",
 pat_h2="Look how far you've come!", pat_build='            You can talk about <b>now</b>, <b>the past</b>, and <b>the future</b>.<br>\n            You can ask, answer, plan, compare, and tell a story.<br>\n            <b>One suitcase → a whole life in English.</b> 🧳→❤️\n',
 pat_tip="<b>This is not the end</b> — it\'s the start. Keep talking, keep reviewing. Your words are yours forever. 🌱",
 yt_lead="Now it's your turn to shine. Fill the gaps, then say your own little speech out loud.",
 yt_build='            My name is <input class="blank" style="width:auto;display:inline-block" placeholder="your name">, and I am learning English.<br><br>\n            One thing I can do now is <input class="blank" style="width:auto;display:inline-block" placeholder="talk about… / ask…">.\n',
 yt_label="Write your own short speech (3 lines about you):", yt_ph="My name is … I can … I want to …",
 checklist=["I can talk about now, past and future","I can tell my own story","I have come so far 🎉","I will keep going with Mia 🌱"],
 words=[w(50,"a party","a happy time with friends","🎉"),w(50,"a lantern","a light in a paper cover","🏮"),
  w(50,"a speech","when you stand and talk to people","🗣️"),w(50,"to arrive","to come to a place","📍"),
  w(50,"a friend","a person you like and trust","🧑‍🤝‍🧑"),w(50,"home","where you belong","🏡"),
  w(50,"proud","very happy about what you did","😊"),w(50,"to belong","to feel this is your place","❤️")])

out=[]
for d in L:
    fn,name,words = build_file(**d)
    out.append((d['n'],fn,name,len(words)))
for n,fn,name,c in out:
    print("%d  %-24s  %s  (%d words)" % (n,fn,name,c))
print("\nGenerated %d lessons" % len(out))
